# Generated by Django 2.2.5 on 2019-09-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='nacionalidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('lugarturistico', models.CharField(max_length=30)),
            ],
        ),
    ]
