# Generated by Django 2.2.5 on 2019-10-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_auto_20190924_0811'),
        ('encuestas', '0004_ciudades'),
    ]

    operations = [
    ]
